apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media-storage

resources:
  - k8s/00-namespace.yaml
  - k8s/01-configmap.yaml
  - k8s/02-secret.yaml
  - k8s/03-storage.yaml
  - k8s/04-postgres.yaml
  - k8s/05-keycloak.yaml
  - k8s/06-backend.yaml
  - k8s/07-frontend.yaml
  - k8s/08-ingress.yaml

commonLabels:
  app.kubernetes.io/name: media-storage
  app.kubernetes.io/managed-by: argocd
