apiVersion: v1
kind: ConfigMap
metadata:
  name: media-storage-config
  namespace: media-storage
data:
  # PostgreSQL
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: "5432"
  POSTGRES_DB: media_storage_db

  # Backend
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/media_storage_db
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: "false"

  # File Upload
  APP_UPLOAD_DIR: /home/uploads/
  SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 500MB
  SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 500MB

  # Logging
  LOGGING_LEVEL_ROOT: INFO
  LOGGING_LEVEL_COM_MEDIA: DEBUG
